### ISSUE TITLE
Set up continuous delivery model similar to Mockito

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-release-tools-example#5]
In order to add end-to-end testing capability to "mockito-release-tools" (https://github.com/mockito/mockito-release-tools/issues/19) we need the example project to adopt continuous delivery similar to Mockito project

Action items:
 - [x] publishing to Bintray (#11, #13 and more)
 - [x] version bumps (#6)
 - [x] extract automation to script plugins (see https://github.com/mockito/mockito-release-tools-example/pull/8)
 - [x] automated releases with Travis CI (in progress, see https://github.com/mockito/mockito-release-tools-example/pull/7)
 - [x] create and publish javadoc and sources (#15)
 - [x] customize pom.xml so that example project is more similar to mockito (#16)
 - [ ] build notable release notes
 - [ ] create "org.mockito.release-tools-examples" group in Maven Central. The goals is to also end-to-end test releasing Central.
 - [ ] move all complexity to release-tools so that it can be reused
